// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApplication1.Models;

public partial class CancellationPolicy
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public int? FullRefundDays { get; set; }
    public int? PartialRefundDays { get; set; }
    public decimal? PartialRefundPercentage { get; set; }
    [JsonIgnore]
    public virtual ICollection<Listing> Listings { get; set; } = new List<Listing>();
}