// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApplication1.Models;

public partial class Currency
{
    public int Id { get; set; }
    public string Code { get; set; }
    public string Symbol { get; set; }
    public string Name { get; set; }
    [JsonIgnore]
    public virtual ICollection<Listing> Listings { get; set; } = new List<Listing>();
    [JsonIgnore]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
    [JsonIgnore]
    public virtual ICollection<ApplicationUser> Users { get; set; } = new List<ApplicationUser>();
}