// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApplication1.Models;

public partial class ListingAmenity
{
    public Guid Id { get; set; }

    public Guid AmenityId { get; set; }

    public Guid ListingId { get; set; }

    [JsonIgnore]
    public virtual Amenity Amenity { get; set; }
    [JsonIgnore]
    public virtual Listing Listing { get; set; }
}