// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApplication1.Models;

public partial class ListingPhoto
{
    public Guid Id { get; set; }

    public Guid ListingId { get; set; }

    public string Url { get; set; }

    public string Caption { get; set; }

    public int? DisplayOrder { get; set; }

    public bool? IsPrimary { get; set; }

    public DateTime? UploadedAt { get; set; }

    [JsonIgnore]
    public virtual Listing Listing { get; set; }
}