// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models;

public partial class Message
{
    public Guid Id { get; set; }

    public Guid SenderId { get; set; }

    public Guid RecipientId { get; set; }

    public Guid? ListingId { get; set; }

    public string Content { get; set; }

    public DateTime? SentTime { get; set; }

    public Guid? ThreadId { get; set; }

    public bool? IsRead { get; set; }

    public virtual Listing Listing { get; set; }
    [NotMapped]
    public virtual ApplicationUser Recipient { get; set; }

    public virtual ApplicationUser Sender { get; set; }
}