// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApplication1.Models;

public partial class PaymentMethod
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string stripeId { get; set; }
    public string stripeCode { get; set; }
    [JsonIgnore]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}