// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApplication1.Models;

public partial class RoomType
{
    public int Id { get; set; }

    public string RoomTypeName { get; set; }

    [JsonIgnore]
    public virtual ICollection<Listing> Listings { get; set; } = new List<Listing>();
}