// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class WishlistItem
{
    public Guid Id { get; set; }

    public Guid WishlistId { get; set; }

    public Guid ListingId { get; set; }

    public DateTime? AddedAt { get; set; }

    public virtual Listing Listing { get; set; }

    public virtual Wishlist Wishlist { get; set; }
}